# gz topic published by the simulator core
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# gz topic published by JointState plugin
# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/joint_states"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: ROS_TO_GZ

# gz topic published by DiffDrive plugin
# - ros_topic_name: "sim/odom"
#   gz_topic_name: "sim/odom"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS

# gz topic published by DiffDrive plugin
# - ros_topic_name: "/sim/tf"
#   gz_topic_name: "/sim/tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/tf_static"
#   gz_topic_name: "/model/diff_drive/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS
# gz topic subscribed to by DiffDrive plugin
# - ros_topic_name: "cmd_vel"
#   gz_topic_name: "cmd_vel"
#   ros_type_name: "geometry_msgs/msg/TwistStamped "
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ